const cities = [
    // Cities in Punjab, India
    { name: 'Amritsar', state: 'Punjab', country: 'India' },
    { name: 'Ludhiana', state: 'Punjab', country: 'India' },
    { name: 'Jalandhar', state: 'Punjab', country: 'India' },
    { name: 'Patiala', state: 'Punjab', country: 'India' },
    { name: 'Bathinda', state: 'Punjab', country: 'India' },
    { name: 'Mohali', state: 'Punjab', country: 'India' },
    { name: 'Hoshiarpur', state: 'Punjab', country: 'India' },
    { name: 'Moga', state: 'Punjab', country: 'India' },
    { name: 'Pathankot', state: 'Punjab', country: 'India' },
    { name: 'Firozpur', state: 'Punjab', country: 'India' },
    { name: 'Phagwara', state: 'Punjab', country: 'India' },
    { name: 'Barnala', state: 'Punjab', country: 'India' },
    { name: 'Faridkot', state: 'Punjab', country: 'India' },
    { name: 'Kapurthala', state: 'Punjab', country: 'India' },
    { name: 'Fazilka', state: 'Punjab', country: 'India' },
    { name: 'Sangrur', state: 'Punjab', country: 'India' },
    { name: 'Tarn Taran', state: 'Punjab', country: 'India' },
    { name: 'Nawanshahr', state: 'Punjab', country: 'India' },
    { name: 'Malerkotla', state: 'Punjab', country: 'India' },
    { name: 'Muktsar', state: 'Punjab', country: 'India' },
    { name: 'Mansa', state: 'Punjab', country: 'India' },
    { name: 'Rupnagar', state: 'Punjab', country: 'India' },
    { name: 'Gurdaspur', state: 'Punjab', country: 'India' },
    { name: 'Abohar', state: 'Punjab', country: 'India' },
    { name: 'Khanna', state: 'Punjab', country: 'India' },

    // Cities in British Columbia, Canada
    { name: 'Vancouver', state: 'British Columbia', country: 'Canada' },
    { name: 'Victoria', state: 'British Columbia', country: 'Canada' },
    { name: 'Surrey', state: 'British Columbia', country: 'Canada' },
    { name: 'Burnaby', state: 'British Columbia', country: 'Canada' },
    { name: 'Richmond', state: 'British Columbia', country: 'Canada' },
    { name: 'Abbotsford', state: 'British Columbia', country: 'Canada' },
    { name: 'Coquitlam', state: 'British Columbia', country: 'Canada' },
    { name: 'Kelowna', state: 'British Columbia', country: 'Canada' },
    { name: 'Langley', state: 'British Columbia', country: 'Canada' },
    { name: 'Saanich', state: 'British Columbia', country: 'Canada' },
    { name: 'Delta', state: 'British Columbia', country: 'Canada' },
    { name: 'Kamloops', state: 'British Columbia', country: 'Canada' },
    { name: 'Nanaimo', state: 'British Columbia', country: 'Canada' },
    { name: 'Chilliwack', state: 'British Columbia', country: 'Canada' },
    { name: 'Maple Ridge', state: 'British Columbia', country: 'Canada' },
    { name: 'Prince George', state: 'British Columbia', country: 'Canada' },
    { name: 'New Westminster', state: 'British Columbia', country: 'Canada' },
    { name: 'Port Coquitlam', state: 'British Columbia', country: 'Canada' },
    { name: 'North Vancouver', state: 'British Columbia', country: 'Canada' },
    { name: 'West Kelowna', state: 'British Columbia', country: 'Canada' },
    { name: 'Port Moody', state: 'British Columbia', country: 'Canada' },
    { name: 'Penticton', state: 'British Columbia', country: 'Canada' },
    { name: 'Terrace', state: 'British Columbia', country: 'Canada' },
    { name: 'Fort St. John', state: 'British Columbia', country: 'Canada' },
    { name: 'Dawson Creek', state: 'British Columbia', country: 'Canada' },
    { name: 'Cranbrook', state: 'British Columbia', country: 'Canada' },

    // Major Cities Worldwide
    { name: 'New York', state: 'New York', country: 'USA' },
    { name: 'Los Angeles', state: 'California', country: 'USA' },
    { name: 'Chicago', state: 'Illinois', country: 'USA' },
    { name: 'Houston', state: 'Texas', country: 'USA' },
    { name: 'Phoenix', state: 'Arizona', country: 'USA' },
    { name: 'Philadelphia', state: 'Pennsylvania', country: 'USA' },
    { name: 'San Antonio', state: 'Texas', country: 'USA' },
    { name: 'San Diego', state: 'California', country: 'USA' },
    { name: 'Dallas', state: 'Texas', country: 'USA' },
    { name: 'San Jose', state: 'California', country: 'USA' },
    { name: 'London', state: '', country: 'United Kingdom' },
    { name: 'Birmingham', state: '', country: 'United Kingdom' },
    { name: 'Manchester', state: '', country: 'United Kingdom' },
    { name: 'Liverpool', state: '', country: 'United Kingdom' },
    { name: 'Edinburgh', state: '', country: 'United Kingdom' },
    { name: 'Tokyo', state: '', country: 'Japan' },
    { name: 'Osaka', state: '', country: 'Japan' },
    { name: 'Kyoto', state: '', country: 'Japan' },
    { name: 'Nagoya', state: '', country: 'Japan' },
    { name: 'Fukuoka', state: '', country: 'Japan' },
    { name: 'Paris', state: '', country: 'France' },
    { name: 'Marseille', state: '', country: 'France' },
    { name: 'Lyon', state: '', country: 'France' },
    { name: 'Toulouse', state: '', country: 'France' },
    { name: 'Nice', state: '', country: 'France' },
    { name: 'Berlin', state: '', country: 'Germany' },
    { name: 'Hamburg', state: '', country: 'Germany' },
    { name: 'Munich', state: '', country: 'Germany' },
    { name: 'Cologne', state: '', country: 'Germany' },
    { name: 'Frankfurt', state: '', country: 'Germany' },
    { name: 'Sydney', state: 'New South Wales', country: 'Australia' },
    { name: 'Melbourne', state: 'Victoria', country: 'Australia' },
    { name: 'Brisbane', state: 'Queensland', country: 'Australia' },
    { name: 'Perth', state: 'Western Australia', country: 'Australia' },
    { name: 'Adelaide', state: 'South Australia', country: 'Australia' },
    { name: 'Toronto', state: 'Ontario', country: 'Canada' },
    { name: 'Vancouver', state: 'British Columbia', country: 'Canada' },
    { name: 'Montreal', state: 'Quebec', country: 'Canada' },
    { name: 'Calgary', state: 'Alberta', country: 'Canada' },
    { name: 'Ottawa', state: 'Ontario', country: 'Canada' },
];